

name: Go CI



# Это вроде триггерами тут тоже называется(при срабатывании них запускается Continuous Integration на GitHub и начинаются проверки)
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]



jobs:
  build-and-test:
    runs-on: ubuntu-latest # Вроде указывают что робот работает на виртуальной машине с Ubuntu
    
    # Если один шаг падает с ошибкой, то и и весь workflow считается проволившемся

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v4  # вроде клонирует  репозиторий на виртуальную машину дабы CI в GitHub увидел код


    - name: Устанавить Go
      uses: actions/setup-go@v5 
      with:
        go-version: '1.27.1' # я вроде одну из последних установил версий




    # Это проверяем форматирование, зависимости испольуземые и тд

    - name: Проверка форматирования (gofmt)
      run: |
      
        # gofmt -l выводит имена файлов, которые не отформатированы
        # Если список не пустой то команда test -z вернет ошибку и workflow будет провален
        test -z "$(gofmt -l .)"



    - name: Статический анализ (go vet)
      run: go vet ./...


    - name: Проверяются зависимостиt (go mod)
      run: |

        # Вроде этой командой модуль go синхронизиурет зависимости
        go mod tidy


        # Проверка что tidy файлы go.mod и go.sum не изменились(дл конца не понял насчет go.sum - вроде хранит хэши скачанных библиотек)
        git diff --exit-code go.mod go.sum

        # Это обязательно для проверки состояний зависимостоей
        go mod verify


    - name: Процесс сборки проекта
      run: go build -v ./...

      
    - name: Запускаются тесты
      run: go test -v ./...